### ISSUE TITLE
QQ使用时，报错语音下载失败，微信则是一个语音文件，可以正常播放

### ISSUE THREAD

**Issue by raind-sjh** [erzaozi/vits-plugin#3]
![image](https://github.com/erzaozi/vits-plugin/assets/168321936/2ffca94c-4085-4316-9a10-04be9d183fe8)

如图所示，无论是手机端还是电脑端的QQ，均显示为语音下载失败

**Comment by raind-sjh** [comment]
![image](https://github.com/erzaozi/vits-plugin/assets/168321936/4c6aa42e-7953-408b-9aed-673b082b5f19)

**Comment by CikeyQi** [comment]
机器人发送到群内的语音可以正常播放吗？

**Comment by raind-sjh** [comment]
![image](https://github.com/erzaozi/vits-plugin/assets/168321936/2e24d712-0d78-4a9e-976b-849263e99574)
经测试，群内语音播放正常

**Comment by CikeyQi** [comment]
和别的大佬讨论了下，可能是发送语音消息时参数有问题导致下载不了语音，应该不是插件这边的问题，QQ私聊语音无法播放问题暂时无法修复，等待后续解决方法
