### ISSUE TITLE
合成失败

### ISSUE THREAD

**Issue by momonini** [erzaozi/vits-plugin#4]
![aaaaaa](https://github.com/erzaozi/vits-plugin/assets/166779595/0dde8d2f-50fd-4ce2-af46-46d7c7cf2207)
![aaaa](https://github.com/erzaozi/vits-plugin/assets/166779595/7f79071b-6d85-44e7-a57a-842b1233a867)
![aaaaa](https://github.com/erzaozi/vits-plugin/assets/166779595/4a919bd3-2939-427f-be64-867b96e512a6)

如图所示，求问原因

**Comment by CikeyQi** [comment]
已更新
