### ISSUE TITLE
返回了wav但转amr失败了

### ISSUE THREAD

**Issue by wzwei1990** [erzaozi/vits-plugin#8]
![image](https://github.com/erzaozi/vits-plugin/assets/41670762/b4bcbe1d-64dd-4db4-a9f2-c483ad225136)

我的是linux安装的ffmpeg 我是了一下命令 ffmpeg -i https://www.modelscope.cn/api/v1/studio/xzjosh/Messi-Bert-VITS2-2.3/gradio/file=/tmp/gradio/7ed4e364d8ca56b3ea95ae6d8334691f22ffa39e/audio.wav -ar 8000 -ab 12.2k audio.amr
这个是成功的

**Comment by CikeyQi** [comment]
转amr失败和插件没有任何关系
