### ISSUE TITLE
语音资源下载异常

### ISSUE THREAD

**Issue by wzwei1990** [erzaozi/vits-plugin#9]
语音发送了 但qq播放不了 请问作者遇到过吗
![12781bb7dd38c6face8b08986bd5d47](https://github.com/erzaozi/vits-plugin/assets/41670762/d927471f-7124-4ecc-94c2-a4a513e37312)

**Comment by CikeyQi** [comment]
你使用的适配器无法在私聊环境下发送.wav格式语音

**Comment by wzwei1990** [comment]
适配器要怎么改呢 求告知



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月4日(周四) 晚上7:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [erzaozi/vits-plugin] 语音资源下载异常 (Issue #9)




 
你使用的适配器无法在私聊环境下发送.wav格式语音
